version: '3.5'

volumes:
  mysql-db:

services:

  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: 'bancoAj5'
      MYSQL_USER: 'banco'
      MYSQL_PASSWORD: 'banco@123'
      MYSQL_ROOT_PASSWORD: 'banco@123'
    ports:
      - "3306:3306"
    networks:
      - projetofinal-controle-trasacao-network
    volumes:
      - mysql-db:/var/lib/mysql

  hotel-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: banco/projetofinal-controle-transacao:latest
    container_name: controle-trasacao-bancaria
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - projetofinal-controle-trasacao-network

networks:
    projetofinal-controle-trasacao-network